name: Deploy

on:
  push:
    branches: [ main ]

jobs:

  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: |
          thavyra/dashboard
          ghcr.io/thavyra/dashboard

    - name: Build and Push
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}   
  
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Deploy Image to Caprover
      uses: caprover/deploy-from-github@v1.1.2
      with:
        server: "${{ secrets.CAPROVER_SERVER }}"
        app: "${{ secrets.CAPROVER_APP_NAME }}"
        token: "${{ secrets.CAPROVER_APP_TOKEN }}"
        image: ghcr.io/thavyra/dashboard:main
        
      
